ppc64_cpu: Fix function method signature
If HAVE_LINUX_PERF_EVENT_H is not defined, the code fails to
compile, because function do_cpu_frequency() does not have an
Argument, as it has if HAVE_LINUX_PERF_EVENT_H is defined.
This is the error message:

 error: too many arguments to function 'do_cpu_frequency'

This patch simply adds an argument to the function.

Signed-off-by: Breno Leitao <breno.leitao@gmail.com>